apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
        - name: article-service
          image: sh44/article-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_URL
              value: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.qsfzcykajlcfcsitsmco&password=H7lHnNnBeiYkD9xo&prepareThreshold=0
# !!!!!!!!!!!!!!!!!! &prepareThreshold=0 is for the ERROR: prepared statement "S_4" already exists. Maybe remove it later !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#              valueFrom:
#                secretKeyRef:
#                  name: articles-db-credentials
#                  key: database-url
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: article-service
spec:
  selector:
    app: article-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: article-service
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: article-service
  endpoints:
    - port: web
      path: /actuator/prometheus
      interval: 30s
  namespaceSelector:
    matchNames:
      - default