apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: sh44/discovery-service:latest
          ports:
            - containerPort: 8761
          env:
            - name: spring.application.name
              value: discovery-service
            - name: eureka.client.register-with-eureka
              value: "false"
            - name: eureka.client.fetchRegistry
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
