apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sh44/user-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka
            - name: KEYCLOAK_TOKEN_ISSUER_URL
              value: http://keycloak-service:8080/realms/sport-spot-realm
            - name: KEYCLOAK_CLIENT_ID
              value: spring-cloud-client
            - name: KEYCLOAK_CLIENT_SECRET
              value: '**********'
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: KEYCLOAK_BASE_URL
              value: http://keycloak-service:8080
            - name: KEYCLOAK_PUBLIC_KEY
              value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyByM7+RXbgbhsCpLb9fN5zfk2nx39lWCibFhMjWfVrLD/nz8gcbfbow5ZjBcbvKD8nF8NGfvEn/zvvKXLkziArAif9IzCactM1Fbg/+qV36F7OqIaPNFz2N1x05F6ah8wtYfamt/RSFJkyjWVIJCBHmHnYR7m6lZm/bKdFhnGxU1OGOOPjBaww7yurF+Rc4HJo5b2Ge8q/hd9MJsiC2KHP9MOOJgFjgofyFRsidZ5Ng6iDAe9+NcYnhhzJu785KPe8G8OdjTifu0OuTg3SJP2k2Bvz/ZT2F1uRbdgrySxZ3wObDonBud1mLQXfjswHngJ7GbRPMVuS20FGS7Do6BxQIDAQAB
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
