apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
      - name: match-service
        image: sh44/match-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-service:8761/eureka

        - name: SPRING_DATA_URL
#          value: jdbc:postgresql://postgres-service:5432/postgres
          value: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.toqulxidosmsrzepoclb&password=H7lHnNnBeiYkD9xo&prepareThreshold=0
        - name: RAPID_API_KEY
          valueFrom:
            secretKeyRef:
              name: match-details-credentials
              key: api-key
        - name: CURRENT_SEASON
          valueFrom:
            secretKeyRef:
              name: match-details-credentials
              key: season
        - name: LEAGUE
          valueFrom:
            secretKeyRef:
              name: match-details-credentials
              key: league
---
apiVersion: v1
kind: Service
metadata:
  name: match-service
spec:
  selector:
    app: match-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  match-service
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app:  match-service
  endpoints:
    - port: http
      path: /actuator/prometheus